# Generated by Django 4.1.1 on 2022-10-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Nova Prova', max_length=30)),
                ('link', models.CharField(default='n8LbOlX0DD2D1eE4', max_length=20, unique=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_user', models.CharField(choices=[('C', 'Criador'), ('A', 'Aluno')], max_length=1)),
                ('tipo_questao', models.CharField(choices=[('tipo1', 'Combo'), ('tipo2', 'Multipla'), ('tipo3', 'Ligar')], max_length=5)),
                ('numero_questao', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('letra_questao', models.CharField(max_length=1)),
                ('texto1', models.TextField(blank=True)),
                ('texto2', models.TextField(blank=True)),
                ('alt_marcada', models.TextField()),
                ('alt_erradas', models.TextField()),
                ('correto', models.BooleanField(default=True)),
                ('id_prova', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elefante.prova')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
