# Generated by Django 4.1 on 2022-09-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id_prova', models.AutoField(primary_key=True, serialize=False)),
                ('questoes', models.TextField()),
            ],
        ),
    ]
