# Generated by Django 4.1 on 2022-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0002_alter_paper_texto1_alter_paper_texto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='correto',
            field=models.BooleanField(null=True),
        ),
    ]
