# Generated by Django 4.1 on 2022-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0003_alter_paper_correto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='correto',
            field=models.BooleanField(default=True),
        ),
    ]
