# Generated by Django 4.1.2 on 2022-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0003_alter_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='L4pv9YpzoBW2KVY8', max_length=20, unique=True),
        ),
    ]
