# Generated by Django 4.1 on 2022-10-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0004_alter_paper_correto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='link',
            field=models.TextField(default='', editable=False),
        ),
    ]
