# Generated by Django 4.1.2 on 2022-10-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elefante', '0004_alter_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id_prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elefante.prova'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prova',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='3aXnv3xAvo5qmPNR', max_length=20, unique=True),
        ),
    ]
