# Generated by Django 4.1.2 on 2022-10-24 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elefante', '0005_alter_paper_id_prova_alter_paper_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='usuario',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='38Omy5MnPBrdZDO4', max_length=20, unique=True),
        ),
    ]
