# Generated by Django 4.1 on 2022-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0005_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
