# Generated by Django 4.1 on 2022-10-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0006_alter_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='', max_length=20),
        ),
    ]
