# Generated by Django 4.1 on 2022-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0007_alter_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='74ML111L0gW1DnXa', max_length=20, unique=True),
        ),
    ]
