# Generated by Django 4.1 on 2022-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0008_alter_prova_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='nome',
            field=models.CharField(default='Nova Prova', max_length=30),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='WR51jPQBvr2nYMkR', max_length=20, unique=True),
        ),
    ]
